# Generated by Django 5.1.5 on 2025-02-13 05:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('g_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('release_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.date.today)),
                ('time_slot', models.CharField(choices=[('10:00 AM - 12:00 PM', '10:00 AM - 12:00 PM'), ('12:00 PM - 2:00 PM', '12:00 PM - 2:00 PM'), ('2:00 PM - 4:00 PM', '2:00 PM - 4:00 PM'), ('4:00 PM - 6:00 PM', '4:00 PM - 6:00 PM'), ('6:00 PM - 8:00 PM', '6:00 PM - 8:00 PM')], max_length=20)),
                ('reserved', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='app.game')),
            ],
            options={
                'unique_together': {('game', 'date', 'time_slot')},
            },
        ),
        migrations.CreateModel(
            name='SlotBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.game')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.slot')),
            ],
        ),
    ]
