# Generated by Django 5.1.6 on 2025-02-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='image',
            field=models.FileField(upload_to=''),
        ),
    ]
