# Generated by Django 5.1.5 on 2025-02-13 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20250213_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='booking_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slot',
            name='date',
            field=models.DateField(),
        ),
    ]
