# Generated by Django 4.2.19 on 2025-02-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_slotbooking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slot',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='slot',
            name='start_time',
        ),
        migrations.AddField(
            model_name='slot',
            name='time_slot',
            field=models.CharField(choices=[('10:00 AM - 12:00 PM', '10:00 AM - 12:00 PM'), ('12:00 PM - 2:00 PM', '12:00 PM - 2:00 PM'), ('2:00 PM - 4:00 PM', '2:00 PM - 4:00 PM'), ('4:00 PM - 6:00 PM', '4:00 PM - 6:00 PM'), ('6:00 PM - 8:00 PM', '6:00 PM - 8:00 PM')], default='2', max_length=20, unique=True),
            preserve_default=False,
        ),
    ]
