# Generated by Django 5.1.6 on 2025-02-13 07:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_slot_booking_time_alter_slot_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='slotbooking',
            name='booking_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
