# Generated by Django 4.2.19 on 2025-02-12 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_slot_game'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='game',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='app.game'),
            preserve_default=False,
        ),
    ]
