# Generated by Django 4.2.19 on 2025-02-12 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_slot_time_slot'),
    ]

    operations = [
        migrations.AddField(
            model_name='slot',
            name='booking_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('game', 'time_slot')},
        ),
    ]
